package nahamawiki.oef.core;

import cpw.mods.fml.common.ModMetadata;
import nahamawiki.oef.OEFCore;
import net.minecraft.util.StatCollector;

public class OEFInfoCore {

	/** MODの情報を登録する */
	public static void registerInfo(ModMetadata meta) {
		meta.modId = OEFCore.MODID;
		meta.name = OEFCore.MODNAME;
		meta.description = StatCollector.translateToLocal("info.oef.metadescription");
		meta.version = OEFCore.VERSION;
		meta.url = "http://www63.atwiki.jp/akasatanahama/";
		meta.updateUrl = "https://dl.dropboxusercontent.com/s/p1w2kdwh72n7tpd/OEFUpdate.json";
		meta.authorList.add("Akasata Nahama Wiki's Managers");
		meta.authorList.add("Tom Kate");
		meta.authorList.add("Akasata Nahama");
		meta.credits = "";
		meta.logoFile = "assets/oef/logo.png";
		meta.autogenerated = false;
	}

}
